### PR TITLE
Big refresh, slightly breaking

### LINKED ISSUE #9: Refresh package
Before I add the ADTypes binding of #8, I would love to do a little bit of cleaning up. Add some docs, some more tests, etc. Perhaps even a Documenter website. @michel2323 would that be okay?

### PR DESCRIPTION
**Pull request by gdalle**
Hey there @michel2323!

This PR fixes #9 by modernizing and cleaning up the package, in the hope of getting it the appreciation it deserves. I tried to apply the current best practices in terms of package structure, as described in my blog https://modernjuliaworkflows.github.io/. I also added a lot of documentation, and a few breaking changes which I feel make sense (see below). However, the basic functionalities were not altered.

These changes affect ADNLPModels.jl (ping @amontoison) but the fixes are easy to apply so I'll take care of them if you accept.

**Source code**

- BREAKING: Remove `AbstractColoring`, `AbstractOrdering` and the lists `COLORINGS` and `ORDERINGS`
- BRERAKING: Replace them by single structs `ColoringMethod` and `ColoringOrder` with one string attribute (instead of an abstract type)
- BREAKING: Implement `d1_coloring` and friends as shortcuts to these structs (instead of identical but separate structs)
- BREAKING: Change the `ColPackColoring` to use references instead of length-1 vectors
- Replace `ccall` with the macro `@ccall`
- Structure into subfiles

> Strictly speaking, since nothing was documented, these changes could be considered non-breaking, because in Julia the docs _is_ the API ;)

**Documentation**

- Set up a Documenter.jl pipeline for a proper docs website
- Add tutorial page
- Add API reference page
- Write docstrings for _everything_ (please double check that I understood the code correctly)
- Clean up README

**Tests**

- Fix the source of randomness for the sparse matrix with StableRNGs.jl (otherwise it depends on the value of Julia)
- Adjust the number of colors we expect with each coloring
- Add formal test with Aqua.jl and JET.jl
- Add doctests with Documenter.jl
- Structure into subfiles
- Run Julia 1.6 in CI

**Example**

- Remove example file (see #10)

**Esthetics**

- Add `.JuliaFormatter.toml` file for uniform style enforcement, apply formatting with JuliaFormatter.jl

**Compat**

- Bump version to v0.4.0
- Add compat bounds on Julia stdlibs
- Only test with Aqua.jl and JET.jl on Julia v1.10 and above

**CI**

- Add `dependabot.yml` to track outdated dependencies
- Modernize `Test.yml` and `TagBot.yml`
- Add `Documentation.yml` to build a docs website and deploy it

### CODE REVIEW

**Comment by michel2323** [comment]
LGTM (besides the missing new line in the yml files). As per discussion with @amontoison I'd move the package to the Exanauts org if you don't mind. I added you to this repository so you can push the branch and the CI runs.

**Comment by gdalle** [comment]
Cool, thanks! I'll finish the PR tomorrow. I'm also writing a pure Julia version so we'll be able to compare speed 😊

**Comment by amontoison** [comment]
@gdalle Can you update the Julia wrappers to use the macro `@ccall`?

**Comment by gdalle** [comment]
> LGTM (besides the missing new line in the yml files).

To have passing tests I had to fix the source of randomness generating the sparse matrix (otherwise the results you get depend on the version of Julia). I also had to modify the number of colors accordingly for some coloring algorithms. @michel2323 can you check that it still looks okay? Then I think we're good to merge.

> @gdalle Can you update the Julia wrappers to use the macro @ccall?

@amontoison it's done but I've never written a line of C so please double-check

**Review by amontoison — APPROVED** [review]

**Comment by gdalle** [comment]
@michel2323 should we merge?

**Review by michel2323 — APPROVED** [review]

**Pull request merged**
